### PR TITLE
adding a play ("Marko v pekli" by Iwan Kocherha)

### PR DESCRIPTION
**Pull request by DanilSko**
the auto test have passed

### CODE REVIEW

**Comment by DanilSko** [comment]
shouldn't it appear at the website by now? @cmil  (thanks for the merge!)

**Comment by cmil** [comment]
It's on staging: https://staging.dracor.org/u/kocherha-marko-v-pekli. Did you expect it on dracor.org?

**Comment by DanilSko** [comment]
> It's on staging: https://staging.dracor.org/u/kocherha-marko-v-pekli. Did you expect it on dracor.org?

Well, technically UDraCor is a production corpus (https://dracor.org/u) that was officially launched months ago (in July), so I guess I did expect it there. Could we maybe reroute adding new plays from staging to the main production dracor?

**Comment by cmil** [comment]
Currently we don't do any automatic updates of the production site for any of the corpora. The reason being, that we want to make sure a new TEI file doesn't break anything. So we push it to staging (and for some time now also to dev) but not to production. To bring changes there we refresh the entire corpus from time to time on a as-needed basis (@lehkost usually keeps an eye on that). Now that we have validation in place, we could start to automate the production database updates. But I think it should still be a  two step process with a testing step on staging, and that would require changes in how we process the webhooks triggering the updates.

**Comment by DanilSko** [comment]
ah, ok, thanks for explaining this, I didn't know that. Thats perfectly fine then, there's no urgency or anything, let the updates take their time. Thanks again for help with this!

**Pull request merged**
